apiVersion: v1
kind: ConfigMap
metadata:
   name: order-worker-config
data:
   db_url: "jdbc:postgresql://postgresql-test:5432/mydb"
   db_user_name: "postgres"
   payments_url: "payments-service"
   warehouse_url: "warehouse-service"
   delivery_url: "delivery-service"