#values

#nginx values
nginx-ingress:
  controller:
    enableSnippets: true

fullnameOverride: my-order-worker
namespace: zipper

deployment:
  replicas: 1
  appImage: sergedmitr/order-worker
  appVersion: v1
  appPort: 8080

service:
  appPort: 8082
  serviceType: ClusterIP

ingress:
  hostname: arch.homework
  restrictedLocation: /admin
  restrictedLocationCode: 403
  restrictedLocationMessage: "Go your own way, Stalker!"
  workpath: /otusapp/sadmitriev/(.*)

metrics:
  serviceMonitor:
    enabled: true